# Generated by Django 5.0.7 on 2024-07-30 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country_team', models.CharField(blank=True, max_length=50, null=True)),
                ('olympic_role', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'athletes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('conference', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'schools',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ncaa_sport', models.CharField(max_length=255)),
                ('olympic_sport', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sports',
                'ordering': ['id'],
                'unique_together': {('ncaa_sport', 'olympic_sport')},
            },
        ),
        migrations.CreateModel(
            name='AthleteSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.school')),
            ],
            options={
                'db_table': 'athlete_school',
                'ordering': ['athlete', 'school'],
                'unique_together': {('athlete', 'school')},
            },
        ),
        migrations.CreateModel(
            name='AthleteSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.sport')),
            ],
            options={
                'db_table': 'athlete_sport',
                'ordering': ['athlete', 'sport'],
                'unique_together': {('athlete', 'sport')},
            },
        ),
    ]
